name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        elixir: ["1.12.3", "1.13.4"]
        otp: ["25.0.2", "24.3.4.2"]
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - id: mix-cache
        name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          path: deps

      - name: Install Dependencies
        run: sudo apt-get install -y gcc libc6-dev make mecab libmecab-dev mecab-ipadic-utf8

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Tests
        run: mix test --warnings-as-errors
